# Generated by Django 2.2.4 on 2019-09-03 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctorshots', '0003_auto_20190902_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='Rol',
            field=models.CharField(choices=[('1', 'empleado'), ('2', 'administrador'), ('3', 'usuario')], default='1', max_length=1),
        ),
    ]
