# Generated by Django 2.2.5 on 2019-09-05 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctorshots', '0004_auto_20190903_1551'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuarios',
            old_name='contraseña',
            new_name='clave',
        ),
    ]
