# Generated by Django 2.2.5 on 2019-09-10 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctorshots', '0005_auto_20190905_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='cedula',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
