# Generated by Django 2.2.5 on 2019-09-10 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctorshots', '0006_auto_20190910_1444'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarios',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='cedula',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
