# Generated by Django 2.2.5 on 2019-09-10 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctorshots', '0010_auto_20190910_1508'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuarios',
            name='Rol',
        ),
        migrations.RemoveField(
            model_name='usuarios',
            name='clave',
        ),
        migrations.RemoveField(
            model_name='usuarios',
            name='usuario',
        ),
    ]
