# Generated by Django 2.2.5 on 2019-09-10 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctorshots', '0011_auto_20190910_1544'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarios',
            name='Rol',
            field=models.CharField(choices=[('1', 'empleado'), ('2', 'administrador'), ('3', 'usuario')], default='1', max_length=1),
        ),
        migrations.AddField(
            model_name='usuarios',
            name='usuario',
            field=models.CharField(default='', max_length=45),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='cedula',
            field=models.CharField(default='', max_length=20, unique=True),
        ),
    ]
