# Generated by Django 2.2.5 on 2019-09-10 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctorshots', '0013_usuarios_clave'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='cedula',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='clave',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='usuario',
            field=models.CharField(max_length=45),
        ),
    ]
