# Generated by Django 2.2.5 on 2019-09-11 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctorshots', '0014_auto_20190910_1601'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarios',
            name='nombres',
            field=models.CharField(default='', max_length=50),
        ),
    ]
